# Generated by Django 3.0.3 on 2020-05-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200517_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
