# Generated by Django 3.0.3 on 2020-05-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_delete_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
