# Generated by Django 3.0.6 on 2020-05-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_groupmember_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parentgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_group', to='Group.Group')),
            ],
        ),
    ]
