# Generated by Django 3.0.3 on 2020-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0006_auto_20200514_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='auth',
            field=models.IntegerField(choices=[(0, 'President'), (1, 'Core-Members'), (2, 'Elder'), (3, 'Member')], default=3),
        ),
    ]
