# Generated by Django 3.0.3 on 2020-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0007_auto_20200517_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(default='group_default.jpg', upload_to='group_logo'),
        ),
    ]
