# Generated by Django 3.0.3 on 2020-05-12 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notif',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
