# Generated by Django 3.0.3 on 2020-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
        ('user', '0002_auto_20200512_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='user_tags', to='Tag.Tag'),
        ),
    ]
