# Generated by Django 3.0.5 on 2020-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200510_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not Defined'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
