# Generated by Django 3.0.3 on 2020-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200519_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='regnum',
            field=models.IntegerField(default=0),
        ),
    ]
